version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9123:9123"
    # links:
    #   - backend
    volumes:
      - .:/home/esg
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   depends_on:
  #     - database
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/home/esg
  # database:
  #   image: "postgres:15-alpine"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: bread
  #     POSTGRES_DB: esgdb
